import "./../sass/main.scss";
// Imports of components
import Header from "./_components/Layout/Header";
import Footer from "./_components/Layout/footer";



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
